# Generated by Django 5.1.2 on 2024-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0002_alter_uklad_id_alter_uklad_pola'),
    ]

    operations = [
        migrations.AddField(
            model_name='uklad',
            name='nazwa',
            field=models.CharField(default='Układ', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='uklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
