# Generated by Django 5.1.2 on 2024-12-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0003_uklad_nazwa_alter_uklad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uklad',
            name='nazwa',
            field=models.CharField(default='Układ 1', max_length=30, unique=True),
        ),
    ]
