# Generated by Django 5.1.2 on 2024-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0004_alter_uklad_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uklad',
            name='nazwa',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
