# Generated by Django 5.1.2 on 2024-12-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0006_remove_uklad_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Nowa Gra', max_length=100)),
                ('liczba_graczy', models.IntegerField(default=0)),
                ('data_rozpoczecia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='uklad',
            name='gra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uklady', to='gra.gra'),
        ),
    ]
