# Generated by Django 5.1.2 on 2024-12-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0007_gra_uklad_gra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gra',
            name='nazwa',
        ),
    ]
