# Generated by Django 5.1.2 on 2024-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0009_remove_gra_liczba_graczy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='liczba_graczy',
            field=models.IntegerField(default=0),
        ),
    ]
