# Generated by Django 5.1.2 on 2024-12-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0010_gra_liczba_graczy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gra',
            old_name='liczba_graczy',
            new_name='ilosc_planszy',
        ),
    ]
