# Generated by Django 5.1.2 on 2024-12-27 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0013_rename_kolej_gracza_gra_ilosc_planszy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gra',
            name='data_rozpoczecia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
