# Generated by Django 5.1.2 on 2024-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0014_alter_gra_data_rozpoczecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='kolej_gracza',
            field=models.IntegerField(default=0),
        ),
    ]
