# Generated by Django 5.1.2 on 2025-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0015_gra_kolej_gracza'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='komunikat',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uklad',
            name='pola',
            field=models.CharField(max_length=128),
        ),
    ]
