# Generated by Django 5.1.2 on 2025-01-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0016_gra_komunikat_alter_uklad_pola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uklad',
            name='pola',
            field=models.CharField(max_length=256),
        ),
    ]
