# Generated by Django 5.1.2 on 2025-01-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0018_uklad_trafione_pola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uklad',
            old_name='trafione_pola',
            new_name='trafione',
        ),
        migrations.AddField(
            model_name='uklad',
            name='nietrafione',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
