# Generated by Django 5.1.4 on 2025-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0020_gra_uzytkownik_alter_uklad_gra'),
    ]

    operations = [
        migrations.AddField(
            model_name='uklad',
            name='zatopione',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
