# Generated by Django 5.1.2 on 2025-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gra', '0021_uklad_zatopione'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
